export var listRegistred = [
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
    {
        "username": "JEAN",
        "email": "Du Bois",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://www.nationalgeographic.com/content/dam/animals/thumbs/rights-exempt/mammals/m/mountain-gorilla_thumb.jpg",
    },
    {
        "username": "string",
        "email": "string",
        "birthdate": "string",
        "firstname": "string",
        "lastname": "string",
        "phone_number": "string",
        "license_plate": "string",
        "urlPic": "https://s3.amazonaws.com/spectrumnews-web-assets/wp-content/uploads/2018/11/13154625/20181112-SHANK3monkey-844.jpg",
    },
];
